### ISSUE TITLE
Heroku Deploy Error:  "pysqlite is not supported on Python 3"

### ISSUE THREAD

**Issue by jtjessup** [SFDO-Tooling/mrbelvedere#23]
-----> Python app detected
-----> Installing python-3.6.7
-----> Installing pip
-----> Installing SQLite3
-----> Installing requirements with pip
pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hubzk065/pysqlite/
Push rejected, failed to compile Python app.
Push failed

**Comment by jlantz** [comment]
mrbelvedere doesn't work with Python 3 and likely never will.  We're actually pretty far along in the development process of the replacement for mrbelvedere which will be called MetaDeploy.  I'd recommend waiting until MetaDeploy is ready (likely in a few months), instead of trying to deploy a new instance of mrbelvedere on Heroku now.
